# This file contains values from Cookiecutter

default_context:
  project_name: "test_project"
  project_description: "Awesome `test_project` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "Canspirit.AI"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "mdvohra"
  email: "mdvohra52@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
